### ISSUE TITLE
Build failure with dependent crate and HARFBUZZ_SYS_NO_PKG_CONFIG

### ISSUE THREAD

**Issue by spl** [servo/rust-harfbuzz#137]
I'm fairly new to Rust, so please forgive any stupid errors.

Context:
* macOS 10.14.3
* rustc 1.33.0
* cargo 1.33.0

I'm trying to use `harfbuzz-sys` as a dependency in order to build a Rust crate with C that can `#include hb.h`. In the process, I was trying to use `HARFBUZZ_SYS_NO_PKG_CONFIG` to avoid looking at my `brew`-installed `harfbuzz`.

First, let me start with what works:

```
$ git clone git@github.com:servo/rust-harfbuzz.git
$ cd rust-harfbuzz/harfbuzz-sys
$ export HARFBUZZ_SYS_NO_PKG_CONFIG=1
$ cargo build
```

That builds without a complaint. I even did `cargo build -vv` to inspect it more closely.

Next, this also works:

```
$ cargo new --lib experiment
$ cd experiment
$ echo 'harfbuzz-sys = "0.3.1"' >> Cargo.toml
$ cargo build
```

Finally, this fails:

```
$ cargo new --lib experiment
$ cd experiment
$ echo 'harfbuzz-sys = "0.3.1"' >> Cargo.toml
$ export HARFBUZZ_SYS_NO_PKG_CONFIG=1
$ cargo build
```

This is the relevant error message:

```
config.status: error: cannot find input file: `test/Makefile.in'
make: *** [all] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/harfbuzz-sys-0.3.1/build.rs:31:9
```

I have elided the `configure` output: it is exactly the same as the build without `HARFBUZZ_SYS_NO_PKG_CONFIG=1`.

I wonder if the problem is due to #136, which excluded `harfbuzz/test/*` from the crate. That would explain the difference between building in the repository and building from a dependent crate.

If my conjecture is correct, that brings two questions to mind:
1. Should `HARFBUZZ_SYS_NO_PKG_CONFIG=1` be supported outside of the repository itself?
2. If the answer to the above is yes, can `HARFBUZZ_SYS_NO_PKG_CONFIG=1` be added to the CI to avoid breaking it in the future?

**Comment by jdm** [comment]
Yes and yes. That sounds like a very good idea.

**Comment by jdm** [comment]
Bleah, I'm not sure how to add this to CI in a meaningful way that will catch errors before they are published. A path dependency won't work, since that will happily see all the files in the repository that are excluded by the crate. A crates.io dependency will require publishing the new version before it can be tested, which is a chicken and egg problem.
