### ISSUE TITLE
Provide unicode functions

### ISSUE THREAD

**Issue by raphlinus** [servo/rust-harfbuzz#143]
For correct operation, HarfBuzz requires a number of [Unicode functions](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-unicode.h#L228). The idea is that most users of HarfBuzz already have a heavyweight Unicode library, like ICU or glib available. For Rust use, this presents a bit of a challenge.

The functions are:

* Lookup combining class. This is provided by [unicode-normalization](https://crates.io/crates/unicode-normalization) as a [public method](https://docs.rs/unicode-normalization/0.1.8/unicode_normalization/char/fn.canonical_combining_class.html).

* Lookup general category. The [unicode_categories](https://crates.io/crates/unicode_categories) crate seems to do this lookup, but its API is not compatible; it would have to be adapted. It also appears to be not actively maintained.

* [Mirroring.](http://unicode.org/reports/tr9/#Mirroring) This seems like a pretty straightforward lookup based on the [BidiMirroring.txt](https://www.unicode.org/Public/UCD/latest/ucd/BidiMirroring.txt) file.

* [Script lookup.](http://unicode.org/reports/tr24/) I don't know of any Rust code that does this. The document shows a fair amount of complexity, but I'm not sure how much of that is necessary for HarfBuzz use; it might be that a simple lookup in [Scripts.txt](http://www.unicode.org/Public/UCD/latest/ucd/Scripts.txt) is sufficient.

* Composition. This is the [compose](https://docs.rs/unicode-normalization/0.1.8/unicode_normalization/char/fn.compose.html) method from [unicode-normalization](https://crates.io/crates/unicode-normalization).

* Decomposition. This is the [decompose](https://docs.rs/unicode-normalization/0.1.8/unicode_normalization/char/fn.decompose_canonical.html) method from [unicode-normalization](https://crates.io/crates/unicode-normalization). Note that the ICU implementation appears to apply both canonical and compatibility decompositions, but this is probably not what we want (see [Android patch](https://android.googlesource.com/platform/frameworks/minikin/+/0bbff3a%5E!/) to disable it).

Wiring all this up and writing the missing lookups is not hugely complex, this could be a good "help wanted" issue.

**Comment by raphlinus** [comment]
The [ucd-generate](https://crates.io/crates/ucd-generate) crate could be very useful in creating the lookups from UCD data.

**Comment by raphlinus** [comment]
Digging in a bit further, it seems that unic-ucd is not *yet* suitable. Script lookups are on their roadmap but not yet implemented, and apparently bidi lookups only yield a bool of whether the char is mirrored, not the mirrored counterpart.

One reason I file this as an issue is to ask whether the unicode functions are within the scope of the harfbuzz crate. If the goal is to provide an easy to use solution, I think the answer is probably yes. If the goal is to provide as thin a layer over the "sys" code, the answer is probably no. In the latter case, there's the additional question of whether to provide safe wrappers that can be instantiated. The unicode functions don't present any serious safety issues, they're mostly pure functional lookups.

If they are included, it is to some extent "picking winners," with the risk that there might be multiple implementations in a large app. Additionally, at least script lookups will be very useful to a higher layer.

If I don't get a positive answer here, I'll plan on including unicode functions in skribo.

**Comment by khaledhosny** [comment]
HarfBuzz can also be built with embedded [`ucdn`](https://github.com/grigorig/ucdn) library that provides the Unicode function (just in case this was not already known).

**Comment by raphlinus** [comment]
@khaledhosny I probably should have mentioned that, but (a) this build of harfbuzz does not do that and (b) it's likely that a lot of these functions would get used in other places in a large app, especially normalization. I do think it makes sense to provision these from the Rust ecosystem.

The `ucdn` approach might be expedient though, to get something working.

**Comment by raphlinus** [comment]
My first cut at the unicode functions is here:

https://github.com/linebender/skribo/pull/10

I ran into a number of issues. First, for decomposition, most existing code wanted to provide the recursive decomposition. HarfBuzz needs the raw decomposition (to at most two code points).

Second, none of the existing sources for UCD data were suitable; the lookups I needed were simply not present in either [ucd-generate](https://crates.io/crates/ucd-generate) or [unic-ucd](https://crates.io/crates/unic-ucd). I think it's worth taking a look at this landscape and trying to systematize it, rather than having one-off Python scripts as I've done here.

I'm very happy to rework this into a PR against this repo, but also happy to just keep moving forward; ultimately I don't think it matters very much. We can cross that bridge if and when we ever get to the point where there is another serious user of the harfbuzz crate besides skribo.

**Comment by raphlinus** [comment]
Closing this issue, as it looks like I was mistaken about ucdn, it looks like it is included and I did not indeed need to write my own. There might be some value in bringing that back to cut duplication with functions needed by Rust anyway, but almost certainly not worth bothering with now.
