### ISSUE TITLE
update to harfbuzz 2.5.2

### ISSUE THREAD

**Issue by ratmice** [servo/rust-harfbuzz#157]
It'd be nice to update to the 2.5.2 release which contains workarounds for gcc 4.8 https://github.com/harfbuzz/harfbuzz/issues/1724

I'd do a pull request, but i imagine it's more likely a bigger pain to try and review from a 3rd party, than to actually perform the update process.

**Comment by waywardmonkeys** [comment]
Submitted as PR #158

**Comment by ratmice** [comment]
thank you, fixed by 3b1817f
