### ISSUE TITLE
Consider dropping cmake dependency by using amalgamation source file.

### ISSUE THREAD

**Issue by jrmuizel** [servo/rust-harfbuzz#162]
See: https://github.com/harfbuzz/harfbuzz/issues/1809 and https://github.com/harfbuzz/harfbuzz/blob/master/src/harfbuzz.cc

**Comment by waywardmonkeys** [comment]
This would also help with #166 ... I will look into doing this.

**Comment by waywardmonkeys** [comment]
I've got a prototype of this in #170 ... thoughts welcome.

**Comment by waywardmonkeys** [comment]
This has landed on `master` now! (This issue can be closed.)
