### ISSUE TITLE
Glyph data from Harfbuzz

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#174]
There's a pending PR for harfbuzz, https://github.com/harfbuzz/harfbuzz/pull/2016.

There's other pending PRs for other related functionality, but this seems like it would be of interest to Servo and other Rust people as it might let us drop freetype for outline data?

They'd like comments / feedback on what they're doing and this seems like a way to poke people about it.

@SimonSapin @pcwalton @jrmuizel

**Comment by SimonSapin** [comment]
This can be interesting indeed for some applications where a different rasterizer is used.

For now Servo may still want to use Freetype for hinting: https://github.com/servo/font-kit/wiki/FAQ, though I think it may be worth reconsidering if we can get away with not matching the system’s exact rendering on Linux desktop.

**Comment by waywardmonkeys** [comment]
@SimonSapin Either way, they would like feedback on the API before it lands and is stable.
