### ISSUE TITLE
How to force static linking without HARFBUZZ_SYS_NO_PKG_CONFIG?

### ISSUE THREAD

**Issue by RazrFalcon** [servo/rust-harfbuzz#183]
I want to force static linking via cargo feature.

**Comment by jdm** [comment]
We would accept a PR that adds a feature.

**Comment by RazrFalcon** [comment]
I'm not sure how it should be implemented. All we need to do is to remove `HARFBUZZ_SYS_NO_PKG_CONFIG` completely. I'm not sure why it's there in the first place. If I set `build-native-harfbuzz`, I don't care if it is available as a system library. Maybe it's leftovers from the old versions?
