### ISSUE TITLE
Switch to meson build

### ISSUE THREAD

**Issue by jdm** [servo/rust-harfbuzz#187]
https://github.com/harfbuzz/harfbuzz/wiki/Notes-on-migration-to-meson

**Comment by jdm** [comment]
Even though we use the combined build in build.rs, our linux CI currently runs configure and make. That apparently will need to change for 2.7.0, according to https://github.com/servo/rust-harfbuzz/commit/1caa31a5ab1e3a863b7a39b85374527cc2041811#r41009808.

**Comment by waywardmonkeys** [comment]
This isn't necessary any longer as on Linux, we're not doing a build using `configure` any longer. We're using the system-packaged version to help make sure that we remain compatible with it.

**Comment by mrobinson** [comment]
Isn't this still an issue when building the bundled version of HarffBuzz?

**Comment by waywardmonkeys** [comment]
No. That's using the combined build in the build.rs: https://github.com/servo/rust-harfbuzz/blob/ba107cd2e29e89a5ca35a355d4ee35938dfc3474/harfbuzz-sys/build.rs#L20
