### ISSUE TITLE
Publish new release of harfbuzz-sys

### ISSUE THREAD

**Issue by manuel-rhdt** [servo/rust-harfbuzz#190]
It has been already more than a year since the last version was released on crates.io. The latest version on crates.io does not export bindings to `hb-ot` and `ht-aat` APIs (added in #188). This would be important to properly use e.g. OpenType variations (see e.g. https://harfbuzz.github.io/harfbuzz-hb-ot-var.html#hb-ot-var-get-axis-infos).

Please consider releasing the current `master` branch on crates.io.

**Comment by yisibl** [comment]
Yes, we need it!

**Comment by waywardmonkeys** [comment]
We're finally working towards this. See some discussion in #213.

**Comment by mrobinson** [comment]
A new version of HarfBuzz was just released:  https://github.com/servo/rust-harfbuzz/releases/tag/v0.6.0.
