### ISSUE TITLE
Remove use of `ctest`?

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#200]
@jdm @mbrubeck @Manishearth @sffc The `ctest` crate itself hasn't been maintained since late 2019.

These tests fail depending on which platform and library version is used.

I think it would be easiest to just remove the usage of `ctest` so that CI can be fixed overall. I'm happy to submit the PR and such if there's agreement on that being the right path forward.

Another argument in favor of this is that if you update the `bindgen`, then `ctest` won't parse the newly generated bindings.

**Comment by Manishearth** [comment]
I'm not opposed.

**Comment by waywardmonkeys** [comment]
I've added a commit that does this to PR #198, which updates various things about the CI.

If that is able to land, I have a few other things to submit PRs for as well.

**Comment by sffc** [comment]
Seems good to remove `ctest`, but the Rust bindings do need more testing in general. It would be best to have a test suite that more thoroughly covers the public safe APIs in the `harfbuzz` crate.

**Comment by Manishearth** [comment]
Yeah I would like to have more tests in general if we're removing this
