### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#213]
It would be great to get a new release out and we've been discussing this in various places (#211, #210, elsewhere).

To me, these things need to happen:

* Resolve the issues discussed in #211.
* Switch to a submodule. (#205)
* Update that to current release, but perhaps not generate updated bindings for newer APIs, so that it can continue to work on the version of harfbuzz shipped on current Ubuntu LTS.

Is there anything else?

**Comment by alerque** [comment]
Updating existing APIs to the latest versions but not including new APIs sounds like a really weird state to be in. At least my first reaction would have been to either stay at a version you want to hold to to match the supported Harfbuzz version or fully update. What would be the advantage of a mix-and-match state?

**Comment by waywardmonkeys** [comment]
It brings the updated implementations. My memory is that harfbuzz is pretty strict about API compatibility, so it should just mean that we'd basically be getting the bugfixes.

I'd like to update the API as well, but that would require a bit of work (that can be done) to better fix the CI situation for that.

**Comment by waywardmonkeys** [comment]
I've got a lot of things that I wanted done underway ...

Should we update to Rust 2021 edition?

@mrobinson Do you have anything on your list that isn't already under way in some form?

**Comment by mrobinson** [comment]
This sounds good to me so far. I think it makes sense to have a deeper conversation about:

 1. What version of HarfBuzz to ship
 2. How to decide whether to build a static version of HarffBuzz or to try to statically link to the one on the system

**Comment by waywardmonkeys** [comment]
1. I'm in favor of shipping the current version of harfbuzz and updating more frequently to stay up to date.
2. I'm in favor of always building a static version and not using the one on the system, but there are (good) arguments in either direction.

If we always (or by default) build our own, we are able to make better guarantees that using one version of our crate provides the same experience everywhere. (Others will argue that that isn' t our job, but the packaging people's problem probably.)

If we build our own by default, we can build subsets of the functionality, like leaving out some of the code, allowing for slimmer builds where binary size matters.

I'd be interested in hearing what others like @behdad or @Manishearth think.

**Comment by Manishearth** [comment]
I would use the system one as much as possible.

We could potentially use cargo features to gate newer API features?

I think at the very least we should do a new release that supports the old harfbuzzz with the new changes

**Comment by waywardmonkeys** [comment]
@behdad That means that we'll have to support back to the 2.7.4 release due to that being what ships on Ubuntu ... as long as we're only using stable API, that's no issue, right? Any public API in 2.7.4 is still present?

**Comment by behdad** [comment]
> @behdad That means that we'll have to support back to the 2.7.4 release due to that being what ships on Ubuntu ... as long as we're only using stable API, that's no issue, right? Any public API in 2.7.4 is still present?

Correct.

**Comment by behdad** [comment]
> @behdad That means that we'll have to support back to the 2.7.4 release due to that being what ships on Ubuntu ... as long as we're only using stable API, that's no issue, right? Any public API in 2.7.4 is still present?

Is it possible to conditionally bind the newer API?

**Comment by Manishearth** [comment]
We can do so with Cargo features, yes

**Comment by waywardmonkeys** [comment]
@Manishearth @behdad (@mrobinson) My plan for feature-gating right now is pretty simple:

When we add bindings for something that was introduced in a version later than 2.7.4, we'll add a feature to control access based on the major and minor version that introduced it.

For example, a binding for `hb_font_draw_glyph` would be gated by the feature `harfbuzz-7-0` and `hb_language_matches` by `harfbuzz-5-0`.

Features would chain together, each enabling the one previous, so if we only had those 2 features, then `harfbuzz-7-0` would enable `harfbuzz-5-0`.

When using a build against the bundled sources with feature `bundled` enabled, we would use that to enable the latest feature for the sources bundled with ... so, if we didn't bind anything beyond the above, `bundled` would enable `harfbuzz-7-0` which would enable `harfbuzz-5-0`.

For people using system libraries, we would let them specify the feature to enable based on their build and deployment environment for their application, and then see if someone has a better idea going forward.

In the future, when Ubuntu is updated on GitHub Actions and the 2024 LTS ships with a more recent Harfbuzz than 2.7.4, we can think about what should happen to the baseline at that point.

This lets us allow people using bundled sources and their own builds to take advantage of anything in Harfbuzz, while those using system libraries can also get some of the control that they might need.

Does this sound like an okay direction?

**Comment by behdad** [comment]
That sounds like an excellent plan. Thank you!

**Comment by Manishearth** [comment]
Yep, that was roughly what I was imagining. I think features named `harfbuzz_7_0` etc may be fine.

**Comment by mrobinson** [comment]
Okay. Thanks to the great work by @waywardmonkeys and others, I have finally been able to release a new version of HarfBuzz today: https://github.com/servo/rust-harfbuzz/releases/tag/v0.6.0.
