### ISSUE TITLE
`freetype` vs `freetype-sys`

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#238]
This crate uses FreeType in an optional way to enable the Harfbuzz / FreeType integration.

We currently use the Servo crate `freetype`: https://github.com/servo/rust-freetype.

It has an optional dependency on `freetype-sys`, but doesn't use the code from it. I assume that this was added to take advantage of the code there for optionally building FreeType and linking against it.

`freetype` provides the basic unsafe binding from an old version of bindgen against an old version of FreeType.

`freetype-sys` provides the same unsafe binding, but from a newer version of bindgen and a newer version of FreeType (maybe).  `freetype-sys` has a 0.18 release according to the repository, but not according to crates.io.

There's also a higher level `freetype-rs` which provides a safer API over `freetype-sys`.

Has anyone looked at this or thought about what we should do moving forward?

There should probably be a separate conversation somewhere in Servo land about what they want to do as well and hopefully that would mesh well with whatever we do here.

cc: @jdm @mrobinson

**Comment by waywardmonkeys** [comment]
But it might also be that Servo isn't actually using the FreeType integration in `harfbuzz-sys`, so we can just decide what to do on our own ...

**Comment by mrobinson** [comment]
If we can remove one dependency (on the servo `freetype` in this case) and still keep a reasonable compatibility level then that seems like the optimal solution to me. Any simplification of the dependency graph is high priority in my eyes.

**Comment by waywardmonkeys** [comment]
The 0.18 release of `freetype-sys` just got published after I asked about it 2 weeks ago ... so that allows this to move forward.

That crate needs some love though and we should then also revisit Servo's `freetype` crate at some point...
