### ISSUE TITLE
Crates.io

### ISSUE THREAD

**Issue by Nemikolh** [servo/rust-harfbuzz#39]
Is there any plan to publish this library on crates.io ? I would like to use it and still have the possibility to publish my library on crates.io.

**Comment by jdm** [comment]
I have raised this in the mailing list: https://groups.google.com/forum/#!topic/mozilla.dev.servo/0t0Aq6st4qM

**Comment by Nemikolh** [comment]
Thank you very much ! =D

**Comment by SimonSapin** [comment]
Done! https://crates.io/crates/harfbuzz

https://github.com/servo/servo/pull/6186 makes Servo use the crates.io version so that it doesn’t get out of date.

**Comment by Nemikolh** [comment]
Thanks again ! :smiley:
