### ISSUE TITLE
mingw cross-compilation is broken

### ISSUE THREAD

**Issue by indivisible** [servo/rust-harfbuzz#42]
Cross-compiling with mingw fails, as no `cygpath` command is present on Linux hosts.

Otherwise seems to build just fine.

**Comment by Manishearth** [comment]
cc @klutzy

I'm not sure if we want to support xcompilation _to_ Linux from Windows.

Hm.

**Comment by indivisible** [comment]
Sorry, this is cross compiling to a Windows target from a Linux host.

**Comment by Manishearth** [comment]
Oh, okay.
