### ISSUE TITLE
Build error: "'aclocal-1.14' is missing on your system."

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-harfbuzz#54]
`cargo build` runs fine on my machine, but in `cargo build --target arm-linux-androideabi` the build script fails with stderr as below. What’s `aclocal-1.14`? Do I need to install something?

CC @larsbergstrom @mbrubeck 

```
make[1]: warning: -jN forced in submake: disabling jobserver mode.
/home/simon/projects/servo/deps/rust-harfbuzz/harfbuzz-sys/harfbuzz/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [/home/simon/projects/servo/deps/rust-harfbuzz/harfbuzz-sys/harfbuzz/aclocal.m4] Error 127
make: *** [all] Error 2
```

**Comment by SimonSapin** [comment]
I’ve "fixed" this by installing a `automake-1.14` package from my distro. Why it wasn’t required when not cross-compiling is a mystery to me.

Should we update https://github.com/servo/servo/#prerequisites ?

**Comment by SimonSapin** [comment]
I don’t think more build dependencies is the proper fix. This used to work without.

**Comment by larsbergstrom** [comment]
I remember some changes that @mbrubeck made specifically to avoid accidentally trying to rebuild harfbuzz - maybe we're somehow hitting that issue again?
https://github.com/servo/rust-harfbuzz/commit/be0955b890910c9572f374fd4f87ce4e456d17ae

**Comment by SimonSapin** [comment]
I was gonna bisect this but I didn’t manage to reproduce this error :/

(Also, I was wrong earlier today: this is not the same error as happening in https://github.com/servo/servo/pull/8446#issuecomment-159695436)

**Comment by mbrubeck** [comment]
Automake *shouldn't* need to run at all, because the generated files are checked in to the repo. But git doesn't preserve time stamps, so it may write the files to disk with time stamps that cause Make to try to regenerate them. There's a `touch` command in `.travis.yml` to work around this.

**Comment by SimonSapin** [comment]
Ah, that explains why I can't reproduce the issue.

Does changing target affect this? Should that command be part of `makefile.cargo`?

**Comment by mbrubeck** [comment]
Yes, moving the `touch` command to build.rs or makefile.cargo would probably fix this, though care may need to be taken not to cause unnecessary rebuilds when building servo incrementally. (I.e., we should run the command only if the generated files have timestamps older than their dependencies.)

Not sure why `--target` triggered this.

**Comment by jeswin** [comment]
Got the same issue on Ubuntu 15.10 (not cross-compiling). Went away after installing automake, autoconf.
