### ISSUE TITLE
Add servo/cargo-publish to crates.io owners

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-harfbuzz#56]
@mbrubeck, please add `github:servo:cargo-publish` as a crates.io owner of `harfbuzz-sys`. (And publish a new version.) Thanks!

CC https://github.com/servo/servo/pull/8446

**Comment by mbrubeck** [comment]
Oops. I'm out of town until Friday and don't have access to a computer. (Writing this from my phone.) If this is needed before then, you'll need to get a manual change from the cargo team or temporarily use a git dependency. Sorry. :(

**Comment by SimonSapin** [comment]
@alexcrichton Would you do this for us?

**Comment by alexcrichton** [comment]
Done!
