### ISSUE TITLE
native library `freetype` is being linked to by more than one package

### ISSUE THREAD

**Issue by MortimerGoro** [servo/rust-harfbuzz#70]
Hi,

I need to update rust-harfbuzz on Servo, but got this error

```
./mach build --dev
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: native library `freetype` is being linked to by more than one package, and can only be linked to by one package

  freetype-sys v0.4.0
  servo-freetype-sys v4.0.3
```

This is because freetype-sys dependency was added in https://github.com/servo/rust-harfbuzz/pull/69 and Servo/Webrender use servo-freetype-sys instead.

We could add the Freetype C binding to servo-freetype-sys (now it only links) and use that dependency here. Is that the correct way to fix this issue or is there a better way?

**Comment by MortimerGoro** [comment]
Or could we move the dependency to a cargo feature? Not sure if the new Freetype method required in Servo

cc @glennw

**Comment by glennw** [comment]
Do we know which crates depend on ```freetype-sys``` and which depend on ```servo-freetype-sys```? It seems like Servo should only be relying on one of them? Or, put another way, do we know why there is a ```servo-freetype-sys``` at all?

**Comment by MortimerGoro** [comment]
I think that the right solution is to use `freetype` instead of` freetype_sys` (e.g. Webrender uses `freetype` crate https://github.com/servo/webrender/blob/master/webrender/Cargo.toml#L40)

Opened https://github.com/servo/rust-harfbuzz/pull/72 with that change

servo-freetype-sys dependant crates:

```
servo-skia requires ^4.0.0
servo-fontconfig-sys requires ^4.0.0
freetype requires ^4.0.2
skia requires ^2.4.11
```
