### ISSUE TITLE
Two packages on crates.io: harfbuzz and harfbuzz-sys

### ISSUE THREAD

**Issue by behnam** [servo/rust-harfbuzz#75]
Looks like the package was renamed, or something like that, 2 years ago and there's now only one active package, `harfbuzz-sys`, and `harfbuzz` is not maintained, and doesn't exist on master in this repository. This got me very confused when looking for the right package to use.

If I understand the situation correctly, is there any chance we can add mark the status of `harfbuzz` package as *deprecated*, add a note stating this change, or anything else to prevent this?

I assume the general interested is to not *yank* the package to not break it for its users, but, IMHO, new users should be able to find a way to decide which one is the active project.

**Comment by waywardmonkeys** [comment]
I've been updating the `harfbuzz-sys` crate ... and I'd like to see the `harfbuzz` one become active again, but safer bindings on top of `harfbuzz-sys`.

**Comment by mbrubeck** [comment]
The new `harfbuzz` crate has been published.
