### ISSUE TITLE
Link failure when using a newer version of harfbuzz

### ISSUE THREAD

**Issue by zovt** [servo/rust-harfbuzz#76]
When using the `hb_ft_font_create_referenced` function, linking fails with the following:

```
error: linking with `cc` failed: exit code: 1
  |
...
          /home/zovt/dev/tea/src/ui/text.rs:35: undefined reference to `hb_ft_font_create_referenced'
          collect2: error: ld returned 1 exit status
```

This is on Fedora 26, with the following harfbuzz-devel and harfbuzz versions:

```
dnf info harfbuzz-devel harfbuzz
Last metadata expiration check: 1:57:39 ago on Fri 14 Jul 2017 04:22:05 PM EDT.
Installed Packages
Name         : harfbuzz
Version      : 1.4.4
Release      : 1.fc26
Arch         : x86_64
Size         : 652 k
Source       : harfbuzz-1.4.4-1.fc26.src.rpm
Repo         : @System
From repo    : fedora
Summary      : Text shaping library
URL          : http://freedesktop.org/wiki/Software/HarfBuzz
License      : MIT
Description  : HarfBuzz is an implementation of the OpenType Layout engine.

Name         : harfbuzz-devel
Version      : 1.4.4
Release      : 1.fc26
Arch         : x86_64
Size         : 1.4 M
Source       : harfbuzz-1.4.4-1.fc26.src.rpm
Repo         : @System
From repo    : fedora
Summary      : Development files for harfbuzz
URL          : http://freedesktop.org/wiki/Software/HarfBuzz
License      : MIT
Description  : The harfbuzz-devel package contains libraries and header files
             : for developing applications that use harfbuzz.
```

This is fixed in [my fork](https://github.com/zovt/rust-harfbuzz) by bumping the version of harfbuzz used to generate the bindings.

While I understand that this crate is mainly intended for use in Servo, it would be nice if this could be fixed.

**Comment by mbrubeck** [comment]
Thanks for the report!  I'd be happy to accept an upgrade to a new version of Harfbuzz.  When we do this, we should adjust `build.rs` to use the `atleast_version` method from the pkg-config crate to ensure that it finds a compatible version.  If there are breaking changes in the bindings (I haven't looked at the diff yet), then we should also bump the crate version to 0.2.  Feel free to submit a PR for this if you'd like.

**Comment by zovt** [comment]
I can open a cleaned-up PR for it some time this weekend. Thanks for the quick response!

Is there a test suite available to check for breaking API changes?

**Comment by mbrubeck** [comment]
> Is there a test suite available to check for breaking API changes?

No, sorry. This *should* be non-breaking, though, if harfbuzz has managed its versioning correctly.

Actually, I'm curious what caused the link error in your bug report.  The updated bindings don't seem to change the signature of that function...

**Comment by zovt** [comment]
I'd be happy to provide more info if necessary, any commands I should run?

**Comment by khaledhosny** [comment]
`hb_ft_font_create_referenced` is missing` was added to version 0.9.38 in 2015, so if it is missing then this is either an old version of HarfBuzz or badly built one.

**Comment by zovt** [comment]
On my system, the harfbuzz lib shows that it exports that function. Would the fields in the struct types changing cause this incompatibility?

**Comment by zovt** [comment]
Just rebuilt my project with this crate on both my desktop and laptop (which had the error originally). For whatever reason, things seem to be linking properly. Going to close this now, sorry for the churn
