### ISSUE TITLE
Interest in removing the libc dependency?

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#88]
I think all of the types that are currently coming from the `libc` crate could instead be done with `::std::os::raw` instead, letting us drop the `libc` dependency.

Would a pull request doing this be welcome?

**Comment by mbrubeck** [comment]
Yes, moving to `std::os::raw` would be good.  One annoyance is that `c_void` is not compatible between libc and libstd so this needs to be a breaking change.

**Comment by waywardmonkeys** [comment]
This was fixed by pull request #91.
