### ISSUE TITLE
Interest in updating to current harfbuzz?

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#89]
Harfbuzz is up to 1.7.x while this crate is still on 1.4.8.

Would a pull request updating this be welcome?

**Comment by waywardmonkeys** [comment]
My assumption is that I largely need to update the sources that are imported and add any new APIs?

**Comment by emilio** [comment]
Yes, updating it would be great IMO, and your assumption sounds right :)

**Comment by waywardmonkeys** [comment]
Okay, once my existing PRs are merged and I am able to submit the PR for #88 (which would conflict with one of the open PRs), then I'll submit a PR for this.

**Comment by waywardmonkeys** [comment]
I haven't forgotten about this!

I wanted to land all of the changes that happen from bindgen being updated and I think that I now have pull requests in for all of them (except one that I filed as a bug in bindgen instead about `link_name` attributes).

**Comment by waywardmonkeys** [comment]
Fixed by #99.
