### ISSUE TITLE
Interest in using enums and bitflags

### ISSUE THREAD

**Issue by waywardmonkeys** [servo/rust-harfbuzz#90]
There are many constants within the `harfbuzz-sys` crate which would be better expressed as `enum`s or with the `bitflags` crate.

Is this okay to do?

**Comment by mbrubeck** [comment]
Sure!  There's even some support in bindgen for generating bitflags types, I think.

**Comment by waywardmonkeys** [comment]
Looking at this some more, it is tempting to put this into the `harfbuzz` crate which providers safer stuff on top of `harfbuzz-sys`. It is some duplication when setting things up though.

**Comment by waywardmonkeys** [comment]
Closing this now that the `harfbuzz` crate is under way ...
